"use client";

import React, { useState } from "react";
import { X, Copy, Check, Download, FileText, Code } from "lucide-react";

interface AdvisoryModalProps {
  isOpen: boolean;
  onClose: () => void;
  station: {
    name: string;
    state: string;
    lat: number;
    lon: number;
    rainfall: number;
    windSpeed: number;
    temp: number;
  };
  leadDay: number;
  bustProbability: number;
  confidence: number;
  riskCategory: string;
  shapReasons: Array<{ code: string; text: string; contribution: number }>;
  revisions: any;
}

export default function AdvisoryModal({
  isOpen,
  onClose,
  station,
  leadDay,
  bustProbability,
  confidence,
  riskCategory,
  shapReasons,
  revisions,
}: AdvisoryModalProps) {
  const [copied, setCopied] = useState(false);
  const [exportedJson, setExportedJson] = useState(false);

  if (!isOpen) return null;

  const advisoryText = `================================================================================
GOVERNMENT OF INDIA - MINISTRY OF EARTH SCIENCES (MoES)
NATIONAL CENTRE FOR MEDIUM RANGE WEATHER FORECASTING (NCMRWF)
OPERATIONAL DECISION-SUPPORT BULLETIN: MEDIUM-RANGE FORECAST BUST RISK ADVISORY
Generated by ForecastGuard Decision-Support Engine
================================================================================

ISSUED FOR: ${station.name.toUpperCase()} (${station.state.toUpperCase()})
COORDINATES: ${station.lat.toFixed(2)}°N, ${station.lon.toFixed(2)}°E
FORECAST CYCLE: Initialization T=0 | VALIDITY: LEAD DAY ${leadDay} (Medium Range)
TIMESTAMP: ${new Date().toISOString()}

1. FORECAST BUST THREAT ASSESSMENT:
--------------------------------------------------------------------------------
* MODEL-ESTIMATED BUST PROBABILITY : ${(bustProbability * 100).toFixed(1)}%
* COMPLEMENTARY FORECAST CONFIDENCE: ${(confidence * 100).toFixed(1)}%
* OPERATIONAL THREAT CATEGORY      : ${riskCategory.toUpperCase()} RISK
* PREDICTABILITY STATUS            : ${
    bustProbability >= 0.65
      ? "HIGH UNCERTAINTY - MODEL GUIDANCE IS UNRELIABLE. HEAVY REVISIONS EXPECTED."
      : bustProbability >= 0.35
      ? "MODERATE UNCERTAINTY - ENSEMBLE SPREAD VERIFICATION RECOMMENDED."
      : "HIGH CONFIDENCE - NUMERICAL GUIDANCE IS CONSISTENT ACROSS CYCLES."
  }

2. KEY METEOROLOGICAL DRIVERS (SHAP ATTRIBUTIONS):
--------------------------------------------------------------------------------
${
  shapReasons && shapReasons.length > 0
    ? shapReasons
        .map(
          (r, i) =>
            `${i + 1}. [${r.code}] Contribution: ${r.contribution > 0 ? "+" : ""}${r.contribution.toFixed(
              2
            )} | ${r.text}`
        )
        .join("\n")
    : "Standard climatological baseline features active."
}

3. RUN-TO-RUN FORECAST REVISION TRACKING:
--------------------------------------------------------------------------------
* INSTABILITY STATUS: ${revisions?.large_revision ? "WARNING: LARGE REVISION DETECTED ACROSS CYCLES" : "NORMAL INTER-CYCLE EVOLUTION"}
* SHIFT SCORE       : ${revisions?.combined_revision_score ?? "0.45"}
${
  revisions?.runs
    ? revisions.runs
        .map((rn: any) => `  - ${rn.run}: Rain ${rn.rainfall_mm}mm, Wind ${rn.wind_speed_ms}m/s, Temp ${rn.temp_c ?? 25}°C`)
        .join("\n")
    : ""
}

4. DUTY METEOROLOGIST ACTION RECOMMENDATIONS:
--------------------------------------------------------------------------------
${
  bustProbability >= 0.65
    ? "* Cross-verify with NCUM-EPS / NEPS 22-member ensemble cluster distributions.\n* Do not issue deterministic public rainfall extremes without radar/nowcast corroboration.\n* Alert regional Meteorological Centres (RMCs) of high medium-range uncertainty."
    : "* Standard medium-range guidance protocol applies.\n* Monitor upcoming 12Z/00Z cycle for potential synoptic regime divergence."
}

================================================================================
STATUTORY DISCLAIMER:
ForecastGuard is an operational AI/ML decision-support prototype.
Forecast bust warnings do not supersede official statutory weather bulletins issued by IMD/MoES.
================================================================================`;

  const handleCopy = () => {
    navigator.clipboard.writeText(advisoryText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadTxt = () => {
    const blob = new Blob([advisoryText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `ForecastGuard_Advisory_${station.name}_D${leadDay}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadJson = () => {
    const payload = {
      agency: "MoES / NCMRWF",
      system: "ForecastGuard",
      station,
      lead_day: leadDay,
      bust_probability: bustProbability,
      forecast_confidence: confidence,
      risk_category: riskCategory,
      shap_attributions: shapReasons,
      revisions: revisions,
      timestamp: new Date().toISOString(),
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `ForecastGuard_Advisory_${station.name}_D${leadDay}.json`;
    link.click();
    URL.revokeObjectURL(url);
    setExportedJson(true);
    setTimeout(() => setExportedJson(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-4 animate-in fade-in duration-150">
      <div className="glass-feature border border-white/10 rounded-2xl w-full max-w-3xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="p-5 border-b border-white/10 flex justify-between items-center bg-white/[0.02]">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-white/[0.06] border border-white/10 flex items-center justify-center text-white shadow-sm">
              <FileText size={18} />
            </div>
            <div>
              <h2 className="text-[16px] font-bold text-[#E8E8E5] font-sans">
                Operational Forecast Bust Advisory Bulletin
              </h2>
              <span className="text-xs font-mono-tech text-[#8B8B87]">
                MoES / NCMRWF Operational Format
              </span>
            </div>
          </div>

          <button
            onClick={onClose}
            className="w-8 h-8 rounded-full text-[#8B8B87] hover:text-[#E8E8E5] hover:bg-white/[0.06] flex items-center justify-center transition cursor-pointer"
            aria-label="Close Advisory Modal"
          >
            <X size={16} />
          </button>
        </div>

        {/* Advisory Body */}
        <div className="p-6 overflow-y-auto flex-1 bg-black/40">
          <pre className="text-[12.5px] font-mono-tech text-[#D8D8D3] leading-relaxed whitespace-pre-wrap selection:bg-[#E8E8E4] selection:text-[#141414]">
            {advisoryText}
          </pre>
        </div>

        {/* Footer Actions */}
        <div className="p-4 border-t border-white/10 flex flex-wrap justify-between items-center bg-white/[0.02] gap-3">
          <div className="text-xs font-mono-tech text-[#8B8B87] flex items-center gap-2">
            <span className="status-dot-active" />
            <span>READY FOR DISPATCH TO RMCs</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="px-3.5 py-1.5 rounded-full bg-white/[0.04] hover:bg-white/[0.08] border border-white/10 text-[#E8E8E5] text-xs font-mono-tech flex items-center gap-1.5 transition cursor-pointer"
            >
              {copied ? <Check size={14} className="text-white" /> : <Copy size={14} />}
              <span>{copied ? "Copied" : "Copy"}</span>
            </button>

            <button
              onClick={handleDownloadJson}
              className="px-3.5 py-1.5 rounded-full bg-white/[0.04] hover:bg-white/[0.08] border border-white/10 text-[#E8E8E5] text-xs font-mono-tech flex items-center gap-1.5 transition cursor-pointer"
            >
              <Code size={14} />
              <span>{exportedJson ? "Exported" : "JSON"}</span>
            </button>

            <button
              onClick={handleDownloadTxt}
              className="px-4 py-1.5 rounded-full bg-[#E8E8E4] text-[#141414] font-semibold border border-white text-xs font-mono-tech flex items-center gap-1.5 transition hover:bg-white cursor-pointer shadow-sm"
            >
              <Download size={14} />
              <span>Download (.txt)</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
