"use client";

import React, { useState } from "react";
import { X, Copy, Check, Download, FileText, AlertTriangle, ShieldCheck, Code } from "lucide-react";

interface AdvisoryModalProps {
  isOpen: boolean;
  onClose: () => void;
  station: {
    name: string;
    state: string;
    lat: number;
    lon: number;
    rainfall: number;
    windSpeed: number;
    temp: number;
  };
  leadDay: number;
  bustProbability: number;
  confidence: number;
  riskCategory: string;
  shapReasons: Array<{ code: string; text: string; contribution: number }>;
  revisions: any;
}

export default function AdvisoryModal({
  isOpen,
  onClose,
  station,
  leadDay,
  bustProbability,
  confidence,
  riskCategory,
  shapReasons,
  revisions,
}: AdvisoryModalProps) {
  const [copied, setCopied] = useState(false);
  const [exportedJson, setExportedJson] = useState(false);

  if (!isOpen) return null;

  const advisoryText = `================================================================================
GOVERNMENT OF INDIA - MINISTRY OF EARTH SCIENCES (MoES)
NATIONAL CENTRE FOR MEDIUM RANGE WEATHER FORECASTING (NCMRWF)
OPERATIONAL DECISION-SUPPORT BULLETIN: MEDIUM-RANGE FORECAST BUST RISK ADVISORY
Generated by ForecastGuard AI (Problem Statement ID: 26079)
================================================================================

ISSUED FOR: ${station.name.toUpperCase()} (${station.state.toUpperCase()})
COORDINATES: ${station.lat.toFixed(2)}°N, ${station.lon.toFixed(2)}°E
FORECAST CYCLE: Initialization T=0 | VALIDITY: LEAD DAY ${leadDay} (Medium Range)
TIMESTAMP: ${new Date().toISOString()}

1. FORECAST BUST THREAT ASSESSMENT:
--------------------------------------------------------------------------------
* MODEL-ESTIMATED BUST PROBABILITY : ${(bustProbability * 100).toFixed(1)}%
* COMPLEMENTARY FORECAST CONFIDENCE: ${(confidence * 100).toFixed(1)}%
* OPERATIONAL THREAT CATEGORY      : ${riskCategory.toUpperCase()} RISK
* PREDICTABILITY STATUS            : ${
    bustProbability >= 0.65
      ? "HIGH UNCERTAINTY - MODEL GUIDANCE IS UNRELIABLE. HEAVY REVISIONS EXPECTED."
      : bustProbability >= 0.35
      ? "MODERATE UNCERTAINTY - ENSEMBLE SPREAD VERIFICATION RECOMMENDED."
      : "HIGH CONFIDENCE - NUMERICAL GUIDANCE IS CONSISTENT ACROSS CYCLES."
  }

2. KEY METEOROLOGICAL DRIVERS (SHAP ATTRIBUTIONS):
--------------------------------------------------------------------------------
${
  shapReasons && shapReasons.length > 0
    ? shapReasons
        .map(
          (r, i) =>
            `${i + 1}. [${r.code}] Contribution: ${r.contribution > 0 ? "+" : ""}${r.contribution.toFixed(
              2
            )} | ${r.text}`
        )
        .join("\n")
    : "Standard climatological baseline features active."
}

3. RUN-TO-RUN FORECAST REVISION TRACKING:
--------------------------------------------------------------------------------
* INSTABILITY STATUS: ${revisions?.large_revision ? "WARNING: LARGE REVISION DETECTED ACROSS CYCLES" : "NORMAL INTER-CYCLE EVOLUTION"}
* SHIFT SCORE       : ${revisions?.combined_revision_score ?? "0.45"}
${
  revisions?.runs
    ? revisions.runs
        .map((rn: any) => `  - ${rn.run}: Rain ${rn.rainfall_mm}mm, Wind ${rn.wind_speed_ms}m/s, Temp ${rn.temp_c ?? 25}°C`)
        .join("\n")
    : ""
}

4. DUTY METEOROLOGIST ACTION RECOMMENDATIONS:
--------------------------------------------------------------------------------
${
  bustProbability >= 0.65
    ? "* Cross-verify with NCUM-EPS / NEPS 22-member ensemble cluster distributions.\n* Do not issue deterministic public rainfall extremes without radar/nowcast corroboration.\n* Alert regional Meteorological Centres (RMCs) of high medium-range uncertainty."
    : "* Standard medium-range guidance protocol applies.\n* Monitor upcoming 12Z/00Z cycle for potential synoptic regime divergence."
}

================================================================================
STATUTORY DISCLAIMER:
ForecastGuard AI is an operational AI/ML decision-support prototype developed
under MoES / NCMRWF Problem Statement 26079. Forecast bust warnings do not
supersede official statutory weather bulletins issued by IMD/MoES.
================================================================================`;

  const handleCopy = () => {
    navigator.clipboard.writeText(advisoryText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadTxt = () => {
    const blob = new Blob([advisoryText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `MoES_ForecastGuard_Advisory_${station.name}_D${leadDay}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadJson = () => {
    const payload = {
      agency: "MoES / NCMRWF",
      system: "ForecastGuard AI",
      problem_statement: 26079,
      station,
      lead_day: leadDay,
      bust_probability: bustProbability,
      forecast_confidence: confidence,
      risk_category: riskCategory,
      shap_attributions: shapReasons,
      revisions: revisions,
      timestamp: new Date().toISOString(),
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `MoES_ForecastGuard_Advisory_${station.name}_D${leadDay}.json`;
    link.click();
    URL.revokeObjectURL(url);
    setExportedJson(true);
    setTimeout(() => setExportedJson(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 backdrop-blur-md p-4">
      <div className="bg-[#0c0e12] border border-[#232732] rounded-[14px] w-full max-w-3xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="p-5 border-b border-[#232732] flex justify-between items-center bg-[#151820]">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-[8px] bg-[#1c212c] border border-[#232732] flex items-center justify-center text-[#e4f222]">
              <FileText size={20} />
            </div>
            <div>
              <h2 className="text-[17px] font-[600] text-[#ffffff]">
                Operational Forecast Bust Advisory Bulletin
              </h2>
              <span className="text-[12px] font-linear-mono text-[#94a3b8]">
                MoES / NCMRWF Format · PS-26079
              </span>
            </div>
          </div>

          <button
            onClick={onClose}
            className="w-9 h-9 rounded-[8px] text-[#94a3b8] hover:text-[#ffffff] hover:bg-[#232732] flex items-center justify-center transition cursor-pointer"
            aria-label="Close Advisory Modal"
          >
            <X size={18} />
          </button>
        </div>

        {/* Advisory Body */}
        <div className="p-6 overflow-y-auto flex-1 bg-[#08090a]">
          <pre className="text-[13px] font-linear-mono text-[#cbd5e1] leading-relaxed whitespace-pre-wrap selection:bg-[#e4f222] selection:text-[#08090a]">
            {advisoryText}
          </pre>
        </div>

        {/* Footer Actions */}
        <div className="p-4 border-t border-[#232732] flex flex-wrap justify-between items-center bg-[#151820] gap-3">
          <div className="text-[12px] font-linear-mono text-[#94a3b8] flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-[#22c55e]"></span>
            <span>READY FOR DISPATCH TO RMCs</span>
          </div>

          <div className="flex items-center gap-2.5">
            <button
              onClick={handleCopy}
              className="btn-ghost text-[13px] min-h-[40px] cursor-pointer"
            >
              {copied ? <Check size={16} className="text-[#22c55e]" /> : <Copy size={16} />}
              <span>{copied ? "Copied to Clipboard!" : "Copy Bulletin"}</span>
            </button>

            <button
              onClick={handleDownloadJson}
              className="btn-ghost text-[13px] min-h-[40px] cursor-pointer"
            >
              <Code size={16} />
              <span>{exportedJson ? "Exported JSON!" : "Export JSON"}</span>
            </button>

            <button
              onClick={handleDownloadTxt}
              className="btn-acid-lime text-[13px] min-h-[40px] cursor-pointer"
            >
              <Download size={16} />
              <span>Download (.txt)</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
