"use client";

import React, { useState } from "react";
import { X, Copy, Check, Download, FileText, AlertTriangle } from "lucide-react";

interface AdvisoryModalProps {
  isOpen: boolean;
  onClose: () => void;
  station: {
    name: string;
    state: string;
    lat: number;
    lon: number;
    rainfall: number;
    windSpeed: number;
    temp: number;
  };
  leadDay: number;
  bustProbability: number;
  confidence: number;
  riskCategory: string;
  shapReasons: Array<{ code: string; text: string; contribution: number }>;
  revisions: any;
}

export default function AdvisoryModal({
  isOpen,
  onClose,
  station,
  leadDay,
  bustProbability,
  confidence,
  riskCategory,
  shapReasons,
  revisions,
}: AdvisoryModalProps) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const advisoryText = `================================================================================
GOVERNMENT OF INDIA - MINISTRY OF EARTH SCIENCES (MoES)
NATIONAL CENTRE FOR MEDIUM RANGE WEATHER FORECASTING (NCMRWF)
OPERATIONAL DECISION-SUPPORT BULLETIN: MEDIUM-RANGE FORECAST BUST RISK ADVISORY
Generated by ForecastGuard AI (Problem Statement ID: 26079)
================================================================================

ISSUED FOR: ${station.name.toUpperCase()} (${station.state.toUpperCase()})
COORDINATES: ${station.lat.toFixed(2)}°N, ${station.lon.toFixed(2)}°E
FORECAST CYCLE: Initialization T=0 | VALIDITY: LEAD DAY ${leadDay} (Medium Range)
TIMESTAMP: ${new Date().toISOString()}

1. FORECAST BUST THREAT ASSESSMENT:
--------------------------------------------------------------------------------
* MODEL-ESTIMATED BUST PROBABILITY : ${(bustProbability * 100).toFixed(1)}%
* COMPLEMENTARY FORECAST CONFIDENCE: ${(confidence * 100).toFixed(1)}%
* OPERATIONAL THREAT CATEGORY      : ${riskCategory.toUpperCase()} RISK
* PREDICTABILITY STATUS            : ${
    bustProbability >= 0.65
      ? "HIGH UNCERTAINTY - MODEL GUIDANCE IS UNRELIABLE. HEAVY REVISIONS EXPECTED."
      : bustProbability >= 0.35
      ? "MODERATE UNCERTAINTY - ENSEMBLE SPREAD VERIFICATION RECOMMENDED."
      : "HIGH CONFIDENCE - NUMERICAL GUIDANCE IS CONSISTENT ACROSS CYCLES."
  }

2. KEY METEOROLOGICAL DRIVERS (SHAP ATTRIBUTIONS):
--------------------------------------------------------------------------------
${
  shapReasons && shapReasons.length > 0
    ? shapReasons
        .map(
          (r, i) =>
            `${i + 1}. [${r.code}] Contribution: ${r.contribution > 0 ? "+" : ""}${r.contribution.toFixed(
              2
            )} | ${r.text}`
        )
        .join("\n")
    : "Standard climatological baseline features active."
}

3. RUN-TO-RUN FORECAST REVISION TRACKING:
--------------------------------------------------------------------------------
* INSTABILITY STATUS: ${revisions?.large_revision ? "WARNING: LARGE REVISION DETECTED ACROSS CYCLES" : "NORMAL INTER-CYCLE EVOLUTION"}
* SHIFT SCORE       : ${revisions?.combined_revision_score ?? "0.45"}
${
  revisions?.runs
    ? revisions.runs
        .map((rn: any) => `  - ${rn.run}: Rain ${rn.rainfall_mm}mm, Wind ${rn.wind_speed_ms}m/s, Temp ${rn.temp_c ?? 25}°C`)
        .join("\n")
    : ""
}

4. DUTY METEOROLOGIST ACTION RECOMMENDATIONS:
--------------------------------------------------------------------------------
${
  bustProbability >= 0.65
    ? "* Cross-verify with NCUM-EPS / NEPS 22-member ensemble cluster distributions.\n* Do not issue deterministic public rainfall extremes without radar/nowcast corroboration.\n* Alert regional Meteorological Centres (RMCs) of high medium-range uncertainty."
    : "* Standard medium-range guidance protocol applies.\n* Monitor upcoming 12Z/00Z cycle for potential synoptic regime divergence."
}

================================================================================
* DISCLAIMER: Research prototype advisory for operational decision-support only.
Official severe weather bulletins are issued exclusively by statutory authorities.
================================================================================`;

  const handleCopy = () => {
    navigator.clipboard.writeText(advisoryText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([advisoryText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `NCMRWF_Bust_Advisory_${station.name}_Day${leadDay}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-[#08090a]/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="linear-card w-full max-w-3xl max-h-[90vh] flex flex-col p-6 shadow-2xl border border-[#383b3f]">
        {/* Modal Header */}
        <div className="flex justify-between items-center border-b border-[#23252a] pb-4 mb-4">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-[6px] bg-[#161718] border border-[#23252a] flex items-center justify-center text-[#e4f222]">
              <FileText size={18} />
            </div>
            <div>
              <h3 className="text-[17px] font-[510] text-[#ffffff] tracking-tight">
                Operational Forecast Bust Advisory Bulletin
              </h3>
              <span className="text-[12px] font-linear-mono text-[#8a8f98]">
                MoES / NCMRWF Decision-Support Protocol
              </span>
            </div>
          </div>

          <button
            onClick={onClose}
            className="w-8 h-8 rounded-[6px] bg-[#161718] border border-[#23252a] text-[#8a8f98] hover:text-[#ffffff] flex items-center justify-center transition cursor-pointer"
            aria-label="Close Modal"
          >
            <X size={16} />
          </button>
        </div>

        {/* Advisory Text Box */}
        <div className="flex-1 overflow-y-auto bg-[#08090a] p-4 rounded-[8px] border border-[#23252a] font-linear-mono text-[12px] text-[#d0d6e0] leading-relaxed select-text">
          <pre className="whitespace-pre-wrap font-inherit">{advisoryText}</pre>
        </div>

        {/* Modal Footer Controls */}
        <div className="flex flex-col sm:flex-row justify-between items-center gap-3 pt-4 border-t border-[#23252a] mt-4">
          <div className="text-[12px] text-[#62666d] italic">
            Ready for dissemination in forecaster shift briefings.
          </div>

          <div className="flex items-center gap-2.5">
            <button
              onClick={handleCopy}
              className="btn-ghost text-[13px] cursor-pointer"
            >
              {copied ? <Check size={14} className="text-[#27a644]" /> : <Copy size={14} />}
              <span>{copied ? "Copied Bulletin" : "Copy to Clipboard"}</span>
            </button>

            <button
              onClick={handleDownload}
              className="btn-acid-lime text-[13px] cursor-pointer"
            >
              <Download size={14} strokeWidth={2.5} />
              <span>Download Bulletin (.txt)</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
