"use client";

import React, { useState } from "react";
import {
  Layers, Code, Sliders, Eye, Copy, Check, Terminal,
  Box, Sparkles, Command, ChevronRight, ToggleLeft,
  ChevronDown, Layout, Shield, Cpu, RefreshCw
} from "lucide-react";

export default function ProductShowcase() {
  const [activeComponent, setActiveComponent] = useState("Button");
  const [buttonVariant, setButtonVariant] = useState<"primary" | "secondary" | "ghost">("primary");
  const [buttonSize, setButtonSize] = useState<"sm" | "md" | "lg">("md");
  const [isLoadingState, setIsLoadingState] = useState(false);
  const [copiedCode, setCopiedCode] = useState(false);

  const generatedCode = `// Generated by INTENT.UI Engine
import { Button } from "@/components/ui/button";

export function ActionTrigger() {
  return (
    <Button
      variant="${buttonVariant}"
      size="${buttonSize}"${isLoadingState ? "\n      loading={true}" : ""}
      onClick={() => executeWorkflow()}
    >
      Deploy Interface
    </Button>
  );
}`;

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCode);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  };

  return (
    <section id="product" className="py-20 md:py-28 bg-[#090909] border-t border-white/[0.08]">
      <div className="max-w-[1360px] mx-auto px-6">
        
        {/* Section Header */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6 mb-12">
          <div>
            <span className="text-[12px] font-mono text-[#8A8A8A] uppercase tracking-wider block mb-2">
              STUDIO INTERFACE
            </span>
            <h2 className="text-[32px] sm:text-[44px] font-[600] tracking-[-0.035em] text-[#F5F5F5] leading-tight">
              An engineering-grade canvas <br />
              for your component hierarchy.
            </h2>
          </div>

          <p className="text-[15px] text-[#8A8A8A] max-w-md leading-relaxed">
            Direct manipulation of design tokens with automatic bidirectional synchronization between your UI and LLM coding agent.
          </p>
        </div>

        {/* Full-Width Application Studio Preview Mockup */}
        <div className="w-full bg-[#111111] border border-white/[0.1] rounded-[14px] overflow-hidden shadow-2xl">
          
          {/* Studio Window Chrome Header */}
          <div className="h-12 border-b border-white/[0.08] bg-[#151515] px-4 flex items-center justify-between text-[12px] font-mono text-[#8A8A8A]">
            <div className="flex items-center gap-3">
              <div className="flex items-center gap-1.5">
                <span className="w-3 h-3 rounded-full bg-white/[0.15]" />
                <span className="w-3 h-3 rounded-full bg-white/[0.15]" />
                <span className="w-3 h-3 rounded-full bg-white/[0.15]" />
              </div>
              <span className="hidden sm:inline-block text-white/[0.2]">|</span>
              <span className="text-[#F5F5F5] font-semibold flex items-center gap-2">
                <Box size={14} className="text-[#6366f1]" />
                intent-studio / src / components / {activeComponent}.tsx
              </span>
            </div>

            <div className="flex items-center gap-3">
              <span className="px-2 py-0.5 rounded bg-white/[0.06] text-[11px] text-white">
                GIT: main (clean)
              </span>
              <span className="hidden md:inline-block text-[#22c55e]">● RUNTIME READY</span>
            </div>
          </div>

          {/* 3-Column Studio Workspace */}
          <div className="grid grid-cols-1 lg:grid-cols-12 min-h-[520px]">
            
            {/* Left Sidebar: Component Tree & Tokens (3 cols) */}
            <div className="lg:col-span-3 border-r border-white/[0.08] bg-[#111111] p-4 flex flex-col justify-between">
              <div className="space-y-4">
                <div className="text-[11px] font-mono text-[#8A8A8A] uppercase tracking-wider">
                  Component Registry
                </div>

                <div className="space-y-1">
                  {[
                    { name: "Button", category: "Actions", active: activeComponent === "Button" },
                    { name: "Input", category: "Forms", active: activeComponent === "Input" },
                    { name: "Dialog", category: "Overlays", active: activeComponent === "Dialog" },
                    { name: "Badge", category: "Display", active: activeComponent === "Badge" },
                    { name: "Command", category: "Navigation", active: activeComponent === "Command" },
                    { name: "Table", category: "Data", active: activeComponent === "Table" },
                  ].map((comp) => (
                    <button
                      key={comp.name}
                      onClick={() => setActiveComponent(comp.name)}
                      className={`w-full text-left px-3 py-2 rounded-[6px] text-[13px] font-mono transition flex items-center justify-between cursor-pointer ${
                        comp.active
                          ? "bg-white/[0.1] text-[#F5F5F5] font-semibold"
                          : "text-[#8A8A8A] hover:text-white hover:bg-white/[0.04]"
                      }`}
                    >
                      <span className="flex items-center gap-2">
                        <span className="text-[#6366f1]">#</span>
                        <span>{comp.name}</span>
                      </span>
                      <span className="text-[10px] text-white/[0.3]">{comp.category}</span>
                    </button>
                  ))}
                </div>

                <div className="pt-4 border-t border-white/[0.08]">
                  <div className="text-[11px] font-mono text-[#8A8A8A] uppercase tracking-wider mb-2">
                    Design Tokens
                  </div>
                  <div className="space-y-1.5 text-[12px] font-mono text-[#8A8A8A]">
                    <div className="flex justify-between py-1 px-2 rounded hover:bg-white/[0.03]">
                      <span>--radius-md</span>
                      <span className="text-white">8px</span>
                    </div>
                    <div className="flex justify-between py-1 px-2 rounded hover:bg-white/[0.03]">
                      <span>--border-width</span>
                      <span className="text-white">1px</span>
                    </div>
                    <div className="flex justify-between py-1 px-2 rounded hover:bg-white/[0.03]">
                      <span>--color-accent</span>
                      <span className="text-[#6366f1] font-bold">#6366F1</span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="pt-4 border-t border-white/[0.08] text-[11px] font-mono text-[#8A8A8A] flex items-center justify-between">
                <span>Schema: v2.4</span>
                <span className="text-[#22c55e]">Synced with Agent</span>
              </div>
            </div>

            {/* Center Canvas: Live Component Stage (5 cols) */}
            <div className="lg:col-span-5 bg-[#090909] p-6 flex flex-col justify-between border-r border-white/[0.08]">
              <div>
                {/* Stage Controls */}
                <div className="flex flex-wrap items-center justify-between gap-3 pb-4 border-b border-white/[0.08] mb-6">
                  <div className="flex items-center gap-2 text-[12px] font-mono text-[#8A8A8A]">
                    <Eye size={14} className="text-[#6366f1]" />
                    <span>CANVAS: ISOLATED STAGE</span>
                  </div>

                  {/* Loading State Toggle */}
                  <button
                    onClick={() => setIsLoadingState(!isLoadingState)}
                    className={`px-2.5 py-1 rounded text-[11px] font-mono transition cursor-pointer flex items-center gap-1.5 ${
                      isLoadingState ? "bg-[#6366f1]/20 text-[#6366f1] border border-[#6366f1]/40" : "bg-white/[0.05] text-[#8A8A8A]"
                    }`}
                  >
                    <span>loading state</span>
                    <span className="font-bold">{isLoadingState ? "ON" : "OFF"}</span>
                  </button>
                </div>

                {/* Stage Center Stage Display */}
                <div className="min-h-[220px] rounded-[10px] border border-dashed border-white/[0.12] bg-[#0e0e0e] flex flex-col items-center justify-center p-8 relative">
                  <div className="absolute top-2 left-2 text-[10px] font-mono text-white/[0.3]">
                    800 × 400 PX
                  </div>

                  {/* Real Dynamic Component Preview */}
                  {buttonVariant === "primary" && (
                    <button
                      className={`font-medium transition shadow-lg cursor-pointer flex items-center gap-2 ${
                        buttonSize === "sm" ? "h-8 px-3 text-[12px] rounded-[6px]" :
                        buttonSize === "lg" ? "h-12 px-6 text-[15px] rounded-[10px]" :
                        "h-10 px-4 text-[13px] rounded-[8px]"
                      } bg-[#F5F5F5] text-[#090909] hover:bg-white`}
                    >
                      {isLoadingState ? <RefreshCw size={14} className="animate-spin" /> : <Sparkles size={14} />}
                      <span>Deploy Interface</span>
                    </button>
                  )}

                  {buttonVariant === "secondary" && (
                    <button
                      className={`font-medium transition border cursor-pointer flex items-center gap-2 ${
                        buttonSize === "sm" ? "h-8 px-3 text-[12px] rounded-[6px]" :
                        buttonSize === "lg" ? "h-12 px-6 text-[15px] rounded-[10px]" :
                        "h-10 px-4 text-[13px] rounded-[8px]"
                      } bg-[#181818] border-white/[0.15] text-[#F5F5F5] hover:bg-[#202020]`}
                    >
                      {isLoadingState ? <RefreshCw size={14} className="animate-spin" /> : <Sparkles size={14} />}
                      <span>Deploy Interface</span>
                    </button>
                  )}

                  {buttonVariant === "ghost" && (
                    <button
                      className={`font-medium transition cursor-pointer flex items-center gap-2 ${
                        buttonSize === "sm" ? "h-8 px-3 text-[12px] rounded-[6px]" :
                        buttonSize === "lg" ? "h-12 px-6 text-[15px] rounded-[10px]" :
                        "h-10 px-4 text-[13px] rounded-[8px]"
                      } bg-transparent text-[#8A8A8A] hover:text-white hover:bg-white/[0.05]`}
                    >
                      {isLoadingState ? <RefreshCw size={14} className="animate-spin" /> : <Sparkles size={14} />}
                      <span>Deploy Interface</span>
                    </button>
                  )}
                </div>
              </div>

              {/* Variant & Size Switchers */}
              <div className="pt-6 border-t border-white/[0.08] space-y-3">
                <div className="flex items-center justify-between text-[12px] font-mono">
                  <span className="text-[#8A8A8A]">variant:</span>
                  <div className="flex gap-1">
                    {(["primary", "secondary", "ghost"] as const).map((v) => (
                      <button
                        key={v}
                        onClick={() => setButtonVariant(v)}
                        className={`px-2.5 py-1 rounded text-[11px] transition cursor-pointer ${
                          buttonVariant === v ? "bg-white text-black font-semibold" : "text-[#8A8A8A] hover:text-white bg-white/[0.03]"
                        }`}
                      >
                        {v}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="flex items-center justify-between text-[12px] font-mono">
                  <span className="text-[#8A8A8A]">size:</span>
                  <div className="flex gap-1">
                    {(["sm", "md", "lg"] as const).map((s) => (
                      <button
                        key={s}
                        onClick={() => setButtonSize(s)}
                        className={`px-2.5 py-1 rounded text-[11px] transition cursor-pointer ${
                          buttonSize === s ? "bg-white text-black font-semibold" : "text-[#8A8A8A] hover:text-white bg-white/[0.03]"
                        }`}
                      >
                        {s}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* Right Inspector: Live Generated Code & LLM Output (4 cols) */}
            <div className="lg:col-span-4 bg-[#111111] p-5 flex flex-col justify-between">
              <div>
                <div className="flex items-center justify-between pb-3 border-b border-white/[0.08] mb-3">
                  <span className="text-[12px] font-mono text-[#8A8A8A] uppercase tracking-wider flex items-center gap-1.5">
                    <Code size={13} className="text-[#6366f1]" /> Code Inspector
                  </span>
                  <button
                    onClick={handleCopy}
                    className="px-2.5 py-1 rounded bg-white/[0.05] hover:bg-white/[0.1] text-[11px] font-mono text-[#8A8A8A] hover:text-white transition flex items-center gap-1 cursor-pointer"
                  >
                    {copiedCode ? <Check size={12} className="text-[#22c55e]" /> : <Copy size={12} />}
                    <span>{copiedCode ? "Copied" : "Copy TSX"}</span>
                  </button>
                </div>

                <pre className="text-[12px] font-mono text-[#F5F5F5] leading-relaxed overflow-x-auto p-3 rounded-[8px] bg-[#090909] border border-white/[0.06]">
                  <code>{generatedCode}</code>
                </pre>

                {/* Micro-Telemetry Checklist */}
                <div className="mt-4 space-y-2">
                  <span className="text-[11px] font-mono text-[#8A8A8A] uppercase tracking-wider block">
                    Verified Checks:
                  </span>
                  <div className="space-y-1.5 text-[12px] font-mono text-[#8A8A8A]">
                    <div className="flex items-center gap-2">
                      <Check size={13} className="text-[#22c55e]" />
                      <span>WCAG 2.1 AAA Contrast Ratio: 14.2:1</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Check size={13} className="text-[#22c55e]" />
                      <span>Full Keyboard Focus Ring (:focus-visible)</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Check size={13} className="text-[#22c55e]" />
                      <span>Zero runtime CSS-in-JS dependencies</span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="pt-4 border-t border-white/[0.08] text-[11px] font-mono text-[#8A8A8A] flex justify-between">
                <span>Bundle Size: 1.2 KB</span>
                <span className="text-[#6366f1]">Ready to Export</span>
              </div>
            </div>

          </div>
        </div>
      </div>
    </section>
  );
}
